version: '3.4'
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ticket-store
      POSTGRES_USER: ticket-store
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: